const KEY='seucusto-pwa-data-v1';const state=JSON.parse(localStorage.getItem(KEY)||'null')||{products:[],materials:[],production:[]};let currentProduct=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const el=id=>document.getElementById(id);function setView(html){el('view').innerHTML=html}
function render(){const tab=document.querySelector('.tabs button.active')?.dataset.tab||'dashboard';if(tab==='dashboard')dashboard();if(tab==='products')products();if(tab==='materials')materials();if(tab==='production')production();if(tab==='more')more()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});
function dashboard(){const low=state.materials.filter(m=>Number(m.stock||0)<=Number(m.min||0)).length;setView('<div class="grid"><div class="card"><div class="muted">Produtos</div><div class="metric">'+state.products.length+'</div></div><div class="card"><div class="muted">Matérias-primas</div><div class="metric">'+state.materials.length+'</div></div><div class="card"><div class="muted">Alertas de estoque</div><div class="metric '+(low?'danger':'success')+'">'+low+'</div></div></div><div class="card" style="margin-top:14px"><h2>Fluxo de teste</h2><p>Cadastre uma matéria-prima, cadastre um produto, abra a composição e informe quantidades e percentuais físicos. O sistema impede concluir uma composição acima de 100% e sinaliza quando ainda falta completar.</p></div>')}
function products(){setView('<div class="row"><div><h2>Produtos</h2><p class="muted">Cadastro e composição.</p></div><button class="primary" id="newProduct">+ Produto</button></div><div class="list">'+(state.products.length?state.products.map(p=>'<div class="card row"><div><strong>'+esc(p.name)+'</strong><div class="muted">'+esc(p.sku||'Sem SKU')+' • '+esc(p.category||'Sem categoria')+'</div></div><div><button class="ghost" onclick="openComposition(\''+p.id+'\')">Composição</button> <button class="ghost" onclick="deleteProduct(\''+p.id+'\')">Excluir</button></div></div>').join(''):'<div class="card empty">Nenhum produto cadastrado.</div>')+'</div>');el('newProduct').onclick=()=>el('productDialog').showModal()}
function materials(){setView('<div class="row"><div><h2>Matérias-primas</h2><p class="muted">Cadastro, custo e estoque mínimo.</p></div><button class="primary" id="newMaterial">+ Matéria-prima</button></div><div class="list">'+(state.materials.length?state.materials.map(m=>'<div class="card"><div class="row"><strong>'+esc(m.name)+'</strong><span>'+money(m.cost)+' / '+esc(m.unit)+'</span></div><div class="muted">'+esc(m.supplier||'Sem fornecedor')+' • '+esc(m.location||'Sem localização')+'</div><div style="margin-top:10px">Estoque: <strong>'+Number(m.stock||0)+'</strong> '+esc(m.unit)+' • mínimo '+Number(m.min||0)+'</div></div>').join(''):'<div class="card empty">Nenhuma matéria-prima cadastrada.</div>')+'</div>');el('newMaterial').onclick=()=>el('materialDialog').showModal()}
function production(){setView('<div class="card"><h2>Produção</h2><p>O módulo de produção será conectado às receitas depois da validação do núcleo de estoque.</p><div class="warning">Nesta versão PWA, a prioridade é testar cadastro, composição, regra dos 100% e persistência local.</div></div>')}
function more(){setView('<div class="grid"><div class="card"><h3>Persistência</h3><p>Os dados ficam no armazenamento local deste navegador para testes offline.</p></div><div class="card"><h3>Próximos módulos</h3><p>Custos fixos e variáveis, mão de obra, embalagem, desperdício, margem/markup, relatórios e PDF Premium serão ligados após a validação do fluxo básico.</p></div></div>')}
el('productForm').onsubmit=e=>{e.preventDefault();state.products.push({id:crypto.randomUUID(),name:el('pName').value.trim(),sku:el('pSku').value.trim(),category:el('pCategory').value.trim(),unit:el('pUnit').value.trim()||'un',components:[]});save();el('productDialog').close();e.target.reset();render()}
el('materialForm').onsubmit=e=>{e.preventDefault();state.materials.push({id:crypto.randomUUID(),name:el('mName').value.trim(),unit:el('mUnit').value.trim()||'un',cost:Number(el('mCost').value),min:Number(el('mMin').value||0),supplier:el('mSupplier').value.trim(),location:el('mLocation').value.trim(),stock:0});save();el('materialDialog').close();e.target.reset();render()}
window.deleteProduct=id=>{if(confirm('Excluir este produto?')){state.products=state.products.filter(p=>p.id!==id);save();render()}}
window.openComposition=id=>{currentProduct=state.products.find(p=>p.id===id);if(!currentProduct)return;composition()}
function composition(){const p=currentProduct,total=p.components.reduce((s,c)=>s+Number(c.percent||0),0),valid=Math.abs(total-100)<.001,over=total>100.001;setView('<div class="row"><div><button class="ghost" id="backProducts">← Produtos</button><h2>'+esc(p.name)+'</h2></div><div class="'+(valid?'success':'')+'">Composição: <strong>'+total.toFixed(2)+'%</strong></div></div><div class="card"><div class="'+(over?'warning':valid?'ok':'warning')+'">'+(over?'A composição ultrapassa 100%. Reduza os percentuais.':valid?'Composição válida: 100%.':'A composição ainda não fecha 100%.')+'</div><div class="progress" style="margin:14px 0"><i style="width:'+Math.min(total,100)+'%"></i></div><div class="composition">'+p.components.map((c,i)=>'<div class="comp-line"><select class="wide" data-i="'+i+'" data-f="material">'+state.materials.map(m=>'<option value="'+m.id+'" '+(m.id===c.materialId?'selected':'')+'>'+esc(m.name)+'</option>').join('')+'</select><input data-i="'+i+'" data-f="qty" type="number" min="0" step="0.0001" value="'+c.qty+'" placeholder="Qtd"><input data-i="'+i+'" data-f="percent" type="number" min="0" max="100" step="0.01" value="'+c.percent+'" placeholder="% físico"><span>'+money((state.materials.find(m=>m.id===c.materialId)?.cost||0)*Number(c.qty||0))+'</span><button class="ghost" onclick="removeComp('+i+')">×</button></div>').join('')+'</div><div class="actions"><button class="ghost" id="addComp">+ Matéria-prima</button><button class="primary" id="saveComp" '+(over?'disabled':'')+'>Salvar composição</button></div></div>');el('backProducts').onclick=products;el('addComp').onclick=()=>{if(!state.materials.length){alert('Cadastre primeiro uma matéria-prima.');return}p.components.push({materialId:state.materials[0].id,qty:0,percent:0});save();composition()};document.querySelectorAll('[data-f]').forEach(x=>x.onchange=()=>{const c=p.components[Number(x.dataset.i)];if(x.dataset.f==='material')c.materialId=x.value;else c[x.dataset.f]=Number(x.value);save();composition()});el('saveComp').onclick=()=>{if(!valid){alert('A composição precisa totalizar exatamente 100%.');return}alert('Composição salva com 100%.');save()}}
window.removeComp=i=>{currentProduct.components.splice(i,1);save();composition()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');window.addEventListener('online',()=>el('status').textContent='Online • dados locais');window.addEventListener('offline',()=>el('status').textContent='Offline • dados neste aparelho');render();